### ISSUE TITLE
Single Variant Enum Bug

### ISSUE THREAD

**Issue by tdbgamer** [morpheusgraphql/morpheus-graphql#738]
I submitted this issue before #721 , but I'm still seeing this problem in `0.20.0`. It seems like it's not making a data constructor for single variant enums.

**Comment by nalchevanidze** [comment]
i think problem is that version `0.20.0` accidentally introduces 'bug'/ new feature in this deprecated function. now it does not declare used input types automatically and requires that you declare them explicitly with  `declareGlobalTypes`.

use combination of `declareGlobalTypes` and `declareLocalTypesInline` should fix it.

**Comment by nalchevanidze** [comment]
generated constructor will be `WtfTESTENUM`

**Comment by tdbgamer** [comment]
Yeah I'm using both of these functions and still experiencing the issue.

**Comment by nalchevanidze** [comment]
as you see i am covering it with test

https://github.com/morpheusgraphql/morpheus-graphql/blob/f8470c010ee50dec8f57b25cb74f4765ccf64646/morpheus-graphql-client/test/Case/Enum/schema.gql#L10-L12

you can use your scenario and open pull request with failing test, after that i can fix it.

**Comment by nalchevanidze** [comment]
could you try https://github.com/morpheusgraphql/morpheus-graphql/releases/tag/0.20.1

**Comment by nalchevanidze** [comment]
hi @tdbgamer.  sorry i have to close it for now. if you provide  reproducible example  as Github repo you can reopen it with a link.

**Comment by tdbgamer** [comment]
Sorry about that, I'll reopen if we run into it again. In the middle of a big production release over the last month or so.
